
generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app: strimzi
 
resources:
  # For the workflow pipeline to work the first resource should be the strimzi operator image.
  - https://github.com/lburgazzoli/strimzi-kafka-operator-builder/releases/download/latest/010-ServiceAccount-strimzi-cluster-operator.yaml
  - https://github.com/lburgazzoli/strimzi-kafka-operator-builder/releases/download/latest/020-ClusterRole-strimzi-cluster-operator-role.yaml
  - https://github.com/lburgazzoli/strimzi-kafka-operator-builder/releases/download/latest/020-RoleBinding-strimzi-cluster-operator.yaml
  - https://github.com/lburgazzoli/strimzi-kafka-operator-builder/releases/download/latest/021-ClusterRole-strimzi-cluster-operator-role.yaml
  - https://github.com/lburgazzoli/strimzi-kafka-operator-builder/releases/download/latest/021-ClusterRoleBinding-strimzi-cluster-operator.yaml
  - https://github.com/lburgazzoli/strimzi-kafka-operator-builder/releases/download/latest/022-ClusterRole-strimzi-cluster-operator-role.yaml
  - https://github.com/lburgazzoli/strimzi-kafka-operator-builder/releases/download/latest/022-RoleBinding-strimzi-cluster-operator.yaml
  - https://github.com/lburgazzoli/strimzi-kafka-operator-builder/releases/download/latest/023-ClusterRole-strimzi-cluster-operator-role.yaml
  - https://github.com/lburgazzoli/strimzi-kafka-operator-builder/releases/download/latest/023-RoleBinding-strimzi-cluster-operator.yaml
  - https://github.com/lburgazzoli/strimzi-kafka-operator-builder/releases/download/latest/030-ClusterRole-strimzi-kafka-broker.yaml
  - https://github.com/lburgazzoli/strimzi-kafka-operator-builder/releases/download/latest/030-ClusterRoleBinding-strimzi-cluster-operator-kafka-broker-delegation.yaml
  - https://github.com/lburgazzoli/strimzi-kafka-operator-builder/releases/download/latest/031-ClusterRole-strimzi-entity-operator.yaml
  - https://github.com/lburgazzoli/strimzi-kafka-operator-builder/releases/download/latest/031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml
  - https://github.com/lburgazzoli/strimzi-kafka-operator-builder/releases/download/latest/033-ClusterRole-strimzi-kafka-client.yaml
  - https://github.com/lburgazzoli/strimzi-kafka-operator-builder/releases/download/latest/033-ClusterRoleBinding-strimzi-cluster-operator-kafka-client-delegation.yaml  
  - https://github.com/lburgazzoli/strimzi-kafka-operator-builder/releases/download/latest/050-ConfigMap-strimzi-cluster-operator.yaml
  - https://github.com/lburgazzoli/strimzi-kafka-operator-builder/releases/download/latest/060-Deployment-strimzi-cluster-operator.yaml
  # enable Strimzi to monitor cluster wide
  - 023-ClusterRoleBinding-strimzi-cluster-operator.yaml
  # enable Strimzi to access resources cluster wide
  - 024-ClusterRoleBinding-strimzi-cluster-operator-namespaced.yaml
patches:
  # the Strimzi-cluster-operator yaml is a convenient way to install the
  # operator, so it includes everything that is needed including the CRDs
  # however in our case, CRD and operators should be kept separated as we
  # want to get the latest CRDs, but we can have a number of operators
  # installed side by side
  - target:
      kind: CustomResourceDefinition
    patch: |-
      $patch: delete
      kind: CustomResourceDefinition
      apiVersion: apiextensions.k8s.io/v1
      metadata:
        name: ".*.rhoc.bf2.dev"
  # By setting the value of the STRIMZI_NAMESPACE environment variable
  # to *, the Cluster Operator will watch resources across all namespaces
  - target:
      group: apps
      kind: Deployment
      name: strimzi-cluster-operator
      version: v1
    patch: |-
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: strimzi-cluster-operator
      spec:
        template:
          spec:
            containers:
            - name: strimzi-cluster-operator
              env:
              - name: STRIMZI_NAMESPACE            
                valueFrom:
                  $patch: delete  
                value: "*"
              - name: STRIMZI_LOG_LEVEL
                valueFrom:
                  configMapKeyRef:
                    name: strimzi-override-config
                    key: log.level
                    optional: true
              resources:
                limits:
                  cpu: "1000m"
                  memory: "384Mi"
                requests:
                  cpu: "100m"
                  memory: "384Mi"