
generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app: strimzi
 
resources:
  - https://github.com/lburgazzoli/strimzi-kafka-operator-builder/releases/download/latest/strimzi-crds-latest.yaml
